### ISSUE TITLE
Proxy support for image previews

### ISSUE THREAD

**Issue by HankAviator** [yzhang-gh/vscode-markdown#947] opened 2021-05-07 07:19 UTC
## Proposal

Setting `http.proxy` in vscode will not make markdown preview to load images that have to be accessed through a proxy. However, exported HTML will load the image. Suggesting a way to preview such images by respecting vscode's proxy settings.

**Comment by yzhang-gh** [comment] 2021-05-07 07:29
I guess this is caused by VS Code itself. Please see https://code.visualstudio.com/docs/languages/markdown#_markdown-preview-security

**Comment by HankAviator** [comment] 2021-05-07 07:33
Thanks. I realised the first link was to my Google Photos pic. I did try another image from Youtube and it worked. Both HTTPS links and kind of confused why it's behaving this way. The first URL is 787 characters long, dunno if it's the cause.

**Comment by yzhang-gh** [comment] 2021-05-07 08:00
There is also the possibility that the URL contains some special characters.

I'm closing this issue as it doesn't seem to be a problem caused by this extension. Feel free to comment again if you have more information.

**Closed by yzhang-gh** 2021-05-07 08:00 UTC
Labels: Issue: Question
