### ISSUE TITLE
Update KaTeX Version

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [yzhang-gh/vscode-markdown#981] opened 2021-07-09 11:11 UTC
## Proposal

Visual Studio Code now [directly supports KaTeX equations in Markdown](https://code.visualstudio.com/updates/v1_58#_math-formula-rendering-in-the-markdown-preview). The built-in KaTeX renderer is newer (0.13.0, latest), supporting some new features such the commutative diagrams (the `CD` environment, see [this documentation](https://www.jmilne.org/not/Mamscd.pdf) for sample codes). However, VSCode still does not (seem to) support custom macros, KaTeX auto-completion, etc, so this extension is still useful. But the version of KaTeX of this extension is old (0.11.1), without support for `CD` environment, for example. Hope that it will be updated soon.

**Comment by Lemmingh** [comment] 2021-07-09 12:52
Duplicate of #943

Please try the latest dev build, which includes KaTeX 0.13.11.
<https://github.com/yzhang-gh/vscode-markdown/blob/f560819acc2175691dd5d5d809e3329c50d18039/package.json#L519>

See also
#955
#967

**Closed by Lemmingh** 2021-07-09 12:52 UTC
Labels: Res: Duplicate

**Comment by Lemmingh** [comment] 2021-07-09 13:02
I'm sorry that we're having trouble in releasing a new version. #966

**Comment by Lemmingh** [comment] 2021-10-30 09:36
> relationship

The math support essentially involves 3 parts:

* Rendering: Compile LaTeX expressions to HTML.

  [Our fork of `markdown-it-katex`](https://github.com/yzhang-gh/markdown-it-katex): <https://github.com/yzhang-gh/vscode-markdown/issues/943#issuecomment-844117075>

* Highlighting: Tokenize and stylize the text in editor.

  TextMate grammar.

* Completion: IntelliSense for LaTeX commands.

  A naive `CompletionItemProvider`.

Unfortunately, they are now implemented by 3 separate components, and I hope we'll be able to organize the internal into one provider.

---

> Will the extension leverage the builtin KaTeX

No. We cannot due to incompatible design.

---

> highlighter

If you're interested in VS Code's architecture of [syntax highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide):

* <https://github.com/microsoft/vscode/issues/77140>

I'd like to migrate to [Semantic Highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) as soon as possible, believing it's the appropriate way to provide syntax highlighting for Markdown. But I have no idea of removing the barrier.

---

> replace them

Hard to say. It depends on VS Code's resolution logic.

Currently, our renderer contributed via [`extendMarkdownIt()`](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins) can override the built-in `vscode.markdown-math`.

But the TextMate grammar contributed via [injection](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) goes conflicting: <https://github.com/yzhang-gh/vscode-markdown/issues/1008#issuecomment-912735309>
