### ISSUE TITLE
Support auto-completion for markdown-links to headers

### ISSUE THREAD

**Issue by klausj1** [yzhang-gh/vscode-markdown#1002] opened 2021-08-21 18:13 UTC
Hi,

it would be great if auto-completion for markdown-links would not only work for files, but also for headers in a file.

So e.g. test.md:
```
# Title 1

## 2

### tit 3

See [here](./test.md/#
```
Code completion after the '#' at the end would suggest #title-1, #2 and #tit-3

Or is this already working and I missed something?

Thanks,
Klaus

**Comment by Lemmingh** [comment] 2021-08-22 01:37
Duplicate of #894?

**Comment by yzhang-gh** [comment] 2021-08-22 02:33
Agree. Let's track this in #894.

**Closed by yzhang-gh** 2021-08-22 02:33 UTC
Labels: Res: Duplicate, Issue: Feature, Area: auto completion
