### ISSUE TITLE
Auto-update for TOC not working on Windows

### ISSUE THREAD

**Issue by gurbindersingh** [yzhang-gh/vscode-markdown#706] opened 2020-05-29 12:57 UTC
#### What is the problem?

Neither the `Update Table of Contents` command, nor the `Toc: Update on Save` feature are working on Windows.

#### How can I reproduce it?

Write a few headings, create a TOC then add or remove a few headings. If auto-update is disabled, run the `Update Table of Contents` command .

#### Is there any error message in the console?

There is no error message in the console.

#### Version Information

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Extension Version: 3.0.0

**Comment by yzhang-gh** [comment] 2020-05-29 16:36
Apparently it is not reproducible. If this is the case, we will see many people complaining about it.

Please try to reinstall the extension. It would be better if you can provide a minimal example (text snippet).

**Comment by gurbindersingh** [comment] 2020-05-29 17:08
I have already tried reinstalling the extension, that didn't work so I installed the last version (2.8.0) instead, which works as expected.

I have been able to reproduce it using the following snippet

```
# H1

## H2

### H3

## H2

### H3

#### H4
```

**Comment by yzhang-gh** [comment] 2020-05-30 02:24
Thanks for the information.

Now I know the reason (the `toc.orderedList` option). It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by gurbindersingh** [comment] 2020-05-30 08:19
Thanks! Seems to be fixed in the [latest version](https://github.com/yzhang-gh/vscode-markdown/actions/runs/119692204)!

**Closed** 2020-06-20 02:20 UTC
Labels: Area: table of contents, Bug, Fixed in dev build
