### ISSUE TITLE
Exported HTML fail to load math style sheets and fonts

### ISSUE THREAD

**Issue by schtonn** [yzhang-gh/vscode-markdown#1127] opened 2022-05-23 12:39 UTC
## Problem

Several days ago, when I refreshed an exported HTML file, it's fonts and formats of all formulas broke without warning. I tried on several other files, and they were broken as well. I did not re-export or modify these files during the process.

This is what I've found in the console.
```
GET file:///(path to HTML file)/fonts/KaTeX_Main-Regular.woff2 net::ERR_FILE_NOT_FOUND
GET https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css net::ERR_CONNECTION_RESET
GET https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.css net::ERR_CONNECTION_RESET
GET https://cdn.jsdelivr.net/gh/Microsoft/vscode/extensions/markdown-language-features/media/markdown.css net::ERR_CONNECTION_RESET
GET https://cdn.jsdelivr.net/gh/Microsoft/vscode/extensions/markdown-language-features/media/highlight.css net::ERR_CONNECTION_RESET
GET https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.js net::ERR_CONNECTION_RESET
```
The ERR_CONNECTION_RESET might just be a problem with my network, but I don't understand about that local font file.

Also, the problem did not resolve after rebooting, connecting to other networks, or changing the option `print.includeVscodeStylesheets`.

## Environment

Markdown All in One:3.4.3
VS Code:1.67.2 x64

**Comment by yzhang-gh** [comment] 2022-05-23 14:22
Can you open any of them in your browser? e.g., https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css

**Comment by Lemmingh** [comment] 2022-05-23 18:50
Looks like commit 3cb5ec58747b773d114ba180cf7087ceb17244cc was not backported to `release/3.4`?

Then, this is probably a duplicate of #986

## Questions

> `ERR_FILE_NOT_FOUND`

Do you have the `vscode.markdown-math` extension enabled?

Its CSS is not portable, and should be stripped off.

---

> `ERR_CONNECTION_RESET`

Are you behind a proxy server? Or do your ISPs interfere with certain TLS connections?

jsDelivr generally expects direct connection. **All KaTeX fonts should be served by jsDelivr CDN.**

**Comment by schtonn** [comment] 2022-05-24 00:18
I did have `vscode.markdown-math` disabled after checking 986, but the same error occured. It may have always been here, only without any significant impact.

As for the probelm `ERR_CONNECTION_RESET`, it seems that jsDelivr CDN has been polluted in China, and it's not a problem with the extension. (https://github.com/jsdelivr/jsdelivr/issues/18397)

**Closed** 2022-05-25 08:23 UTC
Labels: Area: Exporting, Area: Math, Res: External

**Comment by sylin527** [comment] 2022-12-07 04:58
No CDN Dependent Please.
