### ISSUE TITLE
Double dollar-signs break syntax highlighting

### ISSUE THREAD

**Issue by HarryPeach** [yzhang-gh/vscode-markdown#1016] opened 2021-09-25 22:53 UTC
## Problem

Using double-dollar signs breaks syntax highlighting, when it should end the block and highlight normally.

## How to reproduce

Create a KaTeX math block using double dollar-signs and have text after the block (as seen below):
![image](https://user-images.githubusercontent.com/4750998/134787817-50c41474-5b64-4bea-90b0-961277393c96.png)

The syntax highlighting of the rest of the document will be broken, apart from other math blocks.

## Configuration

Default.

## Environment

Version: 3.4.0
![image](https://user-images.githubusercontent.com/4750998/134787836-1453124f-b213-45fc-97d5-4e9218a66535.png)

## Diagnostic data

No error messages

**Comment by Lemmingh** [comment] 2021-09-26 06:35
Duplicate of #1008

**Closed by Lemmingh** 2021-09-26 06:35 UTC
Labels: Res: Duplicate, Area: Math, Area: Editor theming
