### ISSUE TITLE
Latex math \neq not rendering right

### ISSUE THREAD

**Issue by williampayne23** [yzhang-gh/vscode-markdown#349] opened 2018-12-29 13:22 UTC
#### What is the problem?
In Latex mode ≠ character (\neq) doesn't render properly in the markdown preview. It looks like / = instead.

#### How can I reproduce it?
Reproduce it with the markdown
```
$$
\neq
$$
```
And look in the preview.

**Comment by neilsustc** [comment] 2019-01-01 23:48
It is a dulplicate of #252. I have find the root cause now.

**Comment by neilsustc** [comment] 2019-01-02 00:54
Sorry, I meant to say I didn't find the root cause. The referred issue should have been fixed with the new KaTeX package. But it then has the same problem here (rendering to the left)

**Comment by upupming** [comment] 2019-01-11 17:39
I add some `console.log` to see where the problem comes from.

Writing following markdown:

```md

Hello

$$
a \neq b
$$
```

will be rendered to following by VS Code [markdown language features](https://github.com/Microsoft/vscode/blob/master/extensions/markdown-language-features/):

```
<p>Hello</p>
<p><span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>a</mi><mi>e</mi><mi>q</mi><mi>b</mi></mrow><annotation encoding="application/x-tex">a 
eq b
</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="mord mathdefault">a</span><span class="mord mathdefault">e</span><span class="mord mathdefault" style="margin-right:0.03588em;">q</span><span class="mord mathdefault">b</span></span></span></span></span></p>
```

It seems that the `\n` is interpreted as a new line.

However, everything works well in `print.js`, and the printed html file can be rendered properly, it really strange:

![image](https://user-images.githubusercontent.com/24741764/51050089-9e21a580-160a-11e9-8747-95a0df3039c2.png)

I think `\neq` is a very important symbol, so we need further investigating on this issue.

**Comment by upupming** [comment] 2019-01-12 04:18
Okay, I found the root cause of this issue, and I will open a PR soon!

**Closed as completed** 2019-01-19 10:28 UTC
Labels: Res: Duplicate
