### ISSUE TITLE
Way to disable slugifying headings

### ISSUE THREAD

**Issue by damieng** [yzhang-gh/vscode-markdown#1232] opened 2023-02-04 10:37 UTC
### Proposal

Please consider a way to disable slugifying headings.

Right now even if you use the `<!-- no toc -->` or set the toc contents to only be level 1 this extension still slugifies all your headings by adding `<a id="slugified-version-of-your-heading"></a>` to all headings.

This is especially problematic where the same heading is repeated as it generates the same ID and will also collide with id's you set yourself.

### Other information

Some possibilities might be

- An option under slugify style like "None"
- A global disable slugify tag like `<!-- no slugify -->`
- Improving the existing slugify code to only slugify headings that will be in the toc

### Workarounds

I have reverted to `v3.4.0` to allow my document to be generated again but then I lose newer features.

**Comment by yzhang-gh** [comment] 2023-02-04 12:20
Thanks for reaching out.

It is doable, e.g., a slugify option `none` as you suggested. (As a result, the TOC will become plain text, i.e. `toc.plaintext: true`)

Just a bit curious in which cases the headings' id will collide with those that are manually set. And to avoid this, either you can choose a slugify function (e.g. `bitbucket-cloud`) which adds `markdown-header-` prefix to all the headings' id, or you can add some prefix to those manually set id, e.g., `df-` (definition), `fig-`, `table-`.

I was also wondering whether v3.4.0 works for you but v3.5.0 not.

**Comment by damieng** [comment] 2023-02-04 15:03
Thanks for such a quick response.

The markdown I am editing is at https://github.com/ZXSpectrumVault/Manuals/tree/master/Hardware and I used your extension to create the HTML there too using the "Print document to HTML function".

Because I am reproducing an old computer manual I want very specific control over the TOC and there are many duplicate sub-headings. So I created a TOC by hand and put the appropriate id's in by hand as <a name="id"></a> inside the headings.

In 3.4.0 two things were happening:

1. In the case of headings getting ids (slugifying) all the generated ones were prefixed with `-` and so did not conflict
2. Duplicate headings got a `-n` postfix where `n` was a number counting up - possibly because there was a space between the # and the heading text?

So things worked fine.

In 3.5.0 however the prefix is missing so it collides with mine which I can work around as you said by choosing a different slugify format - but also in the case of `##### EXIT CONDITIONS` where that would have resulted in `exit-conditions-2` etc. now it generates multiple `exit-conditions-3`

A simpler fix I guess might be to not slugify headings unless a TOC is being generated. Right now turning off the TOC still slugifies the headings unnecessarily.

**Comment by yzhang-gh** [comment] 2023-02-04 18:04
I see.

> 1. In the case of headings getting ids (slugifying) all the generated ones were prefixed with `-` and so did not conflict - possibly because there was a space between the # and the heading text?

That's because we changed how we handle HTML in the heading. Personally I think the current behavior is "correct".

> 2. Duplicate headings got a `-n` postfix where `n` was a number counting up

This might be a bug. But I cannot reproduce it with a simple document. Could you try to find out a piece of short text which has this issue?

> A simpler fix I guess might be to not slugify headings unless a TOC is being generated. Right now turning off the TOC still slugifies the headings unnecessarily.

It isn't easy under the current implementation which changes the [`markdown-it`](https://github.com/markdown-it/markdown-it) rendering (MD to HTML).

**Comment by damieng** [comment] 2023-02-04 19:23
If I just do this:

```md

# Hello

## Hello there
```

Then it is generating 

```html
<!-- head etc -->
    <body class="vscode-body vscode-light">
        <h1 id="hello">Hello</h1>
<h2 id="hello-there">Hello there</h2>
    </body>
    </html>
```

So even in this case where I'm not wanting a table of contents it is still adding `id="..."` to every single heading even tho it isn't actually creating a table of contents.

It is also adding a stylesheet and JS for "KaTeX" even though I have all the math and KaTeX settings turned off. Not sure if that is related.

**Comment by yzhang-gh** [comment] 2023-02-05 06:08
> But in 3.5.0 it generates:
> 
> ```
> <body class="vscode-body vscode-light">
> <h1 id="hello">Hello</h1>
> <h2 id="hello-there">Hello there</h2>
> <h2 id="hello-there">Hello there</h2>
> ```

Thanks for catching this bug. It has been fixed now.

I have also packaged a standalone [version](https://github.com/yzhang-gh/vscode-markdown/files/10610313/maio-3.5.0_issue1232.zip) that disables all heading IDs. You can try it out.

**Comment by damieng** [comment] 2023-02-05 08:12
Awesome, that standalone version did not generate any ids! :)

**Comment by yzhang-gh** [comment] 2023-02-05 08:24
Nice to hear that. (And thanks for your coffee 😉)

**Closed** 2023-03-26 08:29 UTC
Labels: Needs Discussion, Area: Table of contents
