### ISSUE TITLE
Printing with dark theme is broken!

### ISSUE THREAD

**Issue by tx8821** [yzhang-gh/vscode-markdown#1101] opened 2022-04-01 18:44 UTC
Hi,

I have set VS Code theme to be the (default) dark theme. But when I print (with _Markdown All in One: Print current document to HTML_ command) the output is light document (confirmed both in Edge & Chrome,  As I understand the output styling should match what is in VS Code's preview view??

VERY ANNOYING.

Latest version of VS Code, Windows 11, Chrome & Edge.

**Comment by Lemmingh** [comment] 2022-04-01 18:46
Duplicate of #691

**Closed by Lemmingh** 2022-04-01 18:46 UTC

**Comment by tx8821** [comment] 2022-04-01 18:52
@Lemmingh I don't think my issue is a duplicate... The linked issue is about fenced code blocks and how the mentioned setting affects _only_ that block. But for _all other areas_ the styling should be inherited from VS Code. My issue is that dark styling is NON_EXISTANT AT ALL. If this is a known limitation (since May 2020, i.e. two years already!) than it should be doccumented that this extension DOES NOT SUPPORT DARK MODE AT ALL. Installed for the sole reason of printing. wasted couple of hours just to realize this feater was not even supposed to be working? The description of the extension just plainly lies???

**Comment by Lemmingh** [comment] 2022-04-01 18:53
> the output styling should match what is in VS Code's preview view

No, we cannot. No available VS Code API.

**Comment by tx8821** [comment] 2022-04-01 18:55
The description clearly states: "The exported HTML should look the same as inside VSCode."
This is the reason why I installed. You should make a BIG BOLD disclaimer in description that this extension, when printing, does NOT inherit styles of VS CODE.

**Comment by Lemmingh** [comment] 2022-04-01 18:56
> it should be doccumented

Please look at

https://github.com/yzhang-gh/vscode-markdown/blob/c50fe848fae507597c2b1252c4dbe0708f16bd24/package.nls.json#L33

> Only affects code blocks.

**Comment by tx8821** [comment] 2022-04-01 19:01
@Lemmingh 
Exactly! That's what I'm saying - that setting ONLY affects CODE BLOCK. But what about OTHER areas? Other areas should INHERIT from VS Code, right? Especially when you mention in extension's description that **"The exported HTML should look the same as inside VSCode."**
If it said in description that "The exported HTML will look NOTHING like as inside VSCode" it would be perfectly understandable.

**Comment by Lemmingh** [comment] 2022-04-01 19:03
> The description clearly states: "The exported HTML should look the same as inside VSCode."

I cannot find the sentence in the `README.md`. Where does it come from?

**Comment by tx8821** [comment] 2022-04-01 19:04
Maybe instead of blatantly closing this (and similar) issues within minutes, and redirecting to the (hopelessly) stal;e another issue that doesn't even have a clear formulation of the actual problem, maybe you should REOPEN this issue and try to find a solution to somehow inherit dark stylesheets.

**Comment by tx8821** [comment] 2022-04-01 19:04
I quoted desctiption of the extension in VS Code extensions page

**Comment by tx8821** [comment] 2022-04-01 19:08
With a quick investigation, there is a "vscode-dark" and "vscode-light" mentions in generated html, I think stylsheets are not referenced correctly, but should definitely be fixable. I mean, at least you can manually inject particular stylesheet when in dark mode. What I'm saying is that this issue does not seem IMPOSSIBLE to solve, but it will never be solved if you don't even acknowledge it...

**Comment by tx8821** [comment] 2022-04-01 19:09
So please reopen this issue. Maybe link other related issues to this one, but not link this into that stale one from 2020.

**Comment by Lemmingh** [comment] 2022-04-01 19:16
> I quoted desctiption of the extension in VS Code extensions page

I see. From an old version.

---

> try to find a solution to somehow inherit dark stylesheets.

We cannot.

VS Code is reluctant to expose real value of theme color, and the request in its repo is effectively rejected.

The color values are not defined those stylesheets. In the Markdown preview, they are encapsulated by CSS variables provided by VS Code's webview.

**Comment by Lemmingh** [comment] 2022-04-01 19:44
> at least you can manually inject particular stylesheet when in dark mode. What I'm saying is that this issue does not seem IMPOSSIBLE to solve

Could you elaborate on "particular stylesheet"? Do you mean something like UA style in web browsers, or #822?

---

We already respect VS Code's `markdown.styles` setting

<https://github.com/yzhang-gh/vscode-markdown/blob/fe80c74e8aa2ad5e6f1b03aaac29f209cb4fbebb/src/print.ts#L251>

And style sheets from other extensions

<https://github.com/yzhang-gh/vscode-markdown/blob/fe80c74e8aa2ad5e6f1b03aaac29f209cb4fbebb/src/markdownExtensions.ts#L36-L39>

If we hard-coded another layer, the result would be very confusing.

**Comment by Lemmingh** [comment] 2022-04-01 20:21
> "vscode-dark" and "vscode-light"

They are "theme class" in VS Code's webview. And VS Code's Markdown preview uses them to select color for code blocks, whose definitions are the only things we can get from VS Code's static CSS files so far.

**Comment by Lemmingh** [comment] 2022-04-01 20:36
From an extension's perspective, VS Code does a very good job at protecting its internal values. I do not think it's worth digging into its source code again and again to implement fancy and fragile features. We should spend the limited budget in critical components.

**Comment by yzhang-gh** [comment] 2022-04-02 03:46
Alright, it seems that a lot has happened when I was sleeping (and even a rage 1-star rating).

So first, @tx8821 I would say you are somehow right that the exported HTML is **not** 100% the same as in VS Code (due to some limitations, I will elaborate on it later).

### Background

The VS Code Markdown preview is provided by VS Code itself, which can be extended (syntax, CSS, JS, etc.) by extensions (e.g. [Mermaid diagram](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid), [Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji), [Markdown Preview Github Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles)). _The same Markdown document may appear/render differently according to your installed extensions_, so does the exported HTML, which is quite confusing.

Because an extension cannot get the internally rendered HTML from VS Code, in version 3.0.0, we added code to mimic how VS Code renders Markdown internally, which replicates everything in the exported HTML. It works reasonably well (https://github.com/yzhang-gh/vscode-markdown/issues/686#issuecomment-641925415 "This extension will grab all those styles (so that the HTML looks the same as inside VSCode)").

That is why the full sentence in `README` is "**Compatible** with other installed Markdown plugins (e.g. [Markdown Footnotes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes)) The exported HTML should look the same as inside VS Code."

_(from v3.0.0 changelog)_
<img src="https://github.com/yzhang-gh/vscode-markdown/blob/master/images/md-extension.png?raw=true" width="600">

### The Remaining Problem

However, no matter how close the exported HTML is to that in the VS Code Preview tab, the extension has no access to the general VS Code theme (which has nothing to do with Markdown), which is @Lemmingh emphasized.

This is in fact the same issue as #686 (I will change its description to reflect this), where VS Code refers to a theme-dependent `var(--vscode-textPreformat-foreground)` and it is not accessible through APIs.
While in this issue, the background of the VS Code Markdown preview is just `transparent` (you can check it with the command "Developer: Open Webview Developer Tools"), and the background you see is actually the color of VS Code (`var(--vscode-editor-background)`). (The font color depends on `var(--vscode-editor-foreground)`)

This is what I commented under #686 in 2020
> I did an investigation and it seems that we cannot access the theme color (i.e. `textPreformat-foreground` here) until https://github.com/microsoft/vscode/issues/32813 is solved.

while the upstream VS Code issue is even opened in 2017...

As you said, there might be some ways to solve this without the above APIs (yep, anything is possible). But it may not be practical.
Let's track this issue in #686 (and hope there is a solution later).

---

Just a few personal thoughts here. I made this extension and have been maintaining it for more than 5 years (though I haven't had enough time to make big changes to this extension for a while). It is free, open-source, and I don't make any profit from it (so do all the contributors). There probably exist quite a few bugs and unclear docs. It can be frustrating to find something not working as expected, but I can't understand why it is ever accused of a lie, lie for what? I really don't think this kind of emotional accusation will do any good to the open source community.

**Comment by quinton-ashley** [comment] 2024-01-18 19:52
Even if you can't acess the exact VSCode dark theme that the user is using could you have the extension at least apply _a dark theme_ if the user selected dark theme for export? Otherwise it seems like a major bug.
