### ISSUE TITLE
can this extension format the math formulate

### ISSUE THREAD

**Issue by lancerXXXX** [yzhang-gh/vscode-markdown#754] opened 2020-07-18 12:51 UTC
#### What is the problem?

I write too many formulate and sometimes I paste latex code to my article, so the format will be a problem for me.

**Comment by yzhang-gh** [comment] 2020-07-18 13:45
I am not aware of any _math formatter_ (not LaTeX formatter) available. Duplicate of https://github.com/yzhang-gh/vscode-markdown/issues/643#issuecomment-609687334.

**Closed** 2020-07-18 13:46 UTC
Labels: Area: math, Duplicate
