### ISSUE TITLE
I hope md file name autocompletes can also be added

### ISSUE THREAD

**Issue by wanjm** [yzhang-gh/vscode-markdown#504] opened 2019-08-10 22:41 UTC
now it can auto complete image name ;
I hope md file name autocompletes can also be added, as we need to use md file in link.

**Comment by yzhang-gh** [comment] 2019-08-10 22:44
This is already done in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). Please give it a try.

(Duplicate of #466)

**Comment by yzhang-gh** [comment] 2019-10-11 16:17
Added in v2.5.0

**Closed by yzhang-gh** 2019-10-11 16:17 UTC
Labels: duplicate
