### ISSUE TITLE
Lower case links in TOC don't work

### ISSUE THREAD

**Issue by EvgeniySachkov** [yzhang-gh/vscode-markdown#312] opened 2018-10-29 12:15 UTC
#### What is the problem?
"Markdown: Create Table of Contents" make a tree, but all headers are in lower case. 
Links work at vscode, but doesnt work when I push .md file to git and try to click on the link in browser.

#### How can I reproduce it?
For example:
```
 # Section One
 ## Subsection OneToOne
```

Will be:
```
 - [Section One](#section-one)
     - [Subsection OneToOne](#subsection-onetoone)
```

And it Will Not work in browser (chrome v.69)

To be:
```
 - [Section One](#Section-One)
     - [Subsection OneToOne](#Subsection-OneToOne)
```
And it Will work in browser!

I hope you understand it and will fix :)

#### Is there any error message in the console?
No errors

**Comment by neilsustc** [comment] 2018-10-29 13:05
Could you give more details about "push .md file to git and try to click on the link in browser"?

Do you mean syncing your file to GitHub? I cannot reproduce

---

![image](https://user-images.githubusercontent.com/7588612/47651307-c0169a80-db7a-11e8-8029-757ecd4682e7.png)

![upper 1](https://user-images.githubusercontent.com/7588612/47651466-2bf90300-db7b-11e8-8690-569467c66aa2.gif)

**Comment by EvgeniySachkov** [comment] 2018-10-31 07:20
Sorry, I speak about sync file to the GitLab. And its different.
This case works on GitHub: https://github.com/EvgeniySachkov/Test/blob/master/README.md
But still doesnt work on my corporate version GitLab: https://prnt.sc/lcju7s
When I click on the link nothing happens :(

Could you save upper and lower case in phrase ?
If header is "Работа с Перменнными" -> Link will be (#Работа-с-Переменными)
It would be perfect :)

**Comment by MoonBegonia** [comment] 2019-04-27 14:46
I have the same problem, and the toc auto urlencode mark some link dose't work, i think It would be better to keep the characters as they were.

![test](https://user-images.githubusercontent.com/26798347/56851117-215ad300-693e-11e9-9aea-bd72403c3ea7.gif)

![image](https://user-images.githubusercontent.com/26798347/56851128-3b94b100-693e-11e9-971c-a9d6d8f74f47.png)

**Comment by yzhang-gh** [comment] 2019-04-27 17:22
@MoonBegonia Are you using GitLab?

The anchors are generated in the same way vscode does. So it should work inside vscode.

![toc](https://user-images.githubusercontent.com/7588612/56852904-ccf12c80-6918-11e9-9674-70c465d9dc5a.gif)

If you set `githubCompatibility` to `true`, then the TOC will work on GitHub (not compatible with vscode in some cases).

Now the problem is we don't have an option `gitlabCompatibility` (or the other software you are using).

**Comment by spmeesseman** [comment] 2019-05-18 19:04
Hi, I dont think his is a gitlab compatibility thing?  If I make a simple index.html file served by Apache on Linux, reference links are case sensitive, just like URL's and just like everything else on *nix system.  These generated lower-case links don't work on anything except VSCode viewer and Github.  Adding support for producing the link exactly is it appears in the header text (case included), it will work everywhere,

**Comment by spmeesseman** [comment] 2019-05-18 19:33
I have "refactored this and have it working in a fork, any chance you're interested in the pull request?

All I did was add a boolean parameter in slugify() called changeCase, it defaults to false.  Then in toc.ts I call slugify(anchorText, false).  Then the anchor links get created in the same case as in the header titles, and will work everywhere.

**Comment by yzhang-gh** [comment] 2019-05-18 19:47
Of course. PRs are always welcome 😉

I was thinking about what kind of settings we should introduce. I don't want to have 4 possible combinations of these settings 😂.

Although GitHub will lowercase all the anchors, the uppercase anchors also work (i.e. case insensitive on GitHub). That means GitHub is "compatible" with the case sensitive convention.
Let's make it `markdown.extension.toc.vscodeCompatibility` and default to `false`.

**Comment by spmeesseman** [comment] 2019-05-18 20:35
Thank you!!!!

**Comment by spmeesseman** [comment] 2019-05-18 20:38
Im not sure if it makes a difference, but the case-exact links work in vscode too, so maybe e setting called vscodeCompatibility may be confusing?  Whatever you decide is good with me, i very much appreciate u getting this change into the main line

**Comment by yzhang-gh** [comment] 2019-05-18 21:03
> but the case-exact links work in vscode too

Stupid me 🤦‍♂️. That is even better. Then I decide to always keep the upper/lower-case.

The `githubCompatibility` option was introduced for other differences like whether or not encode the URL.

**Comment by spmeesseman** [comment] 2019-05-19 22:43
so, maybe you're right?  When i open my extension in VSCode Market place "from Visual Studio Code", it doesn't work???  Now I'm confused, that;s complete back asswards logic.  So maybe scratch my last comment, you might want to test for yourself before taking my dumb word for it.  Thanks again!!!!!!!!!

**Comment by yzhang-gh** [comment] 2019-05-20 09:21
The logic to generate anchors is different in different Markdown renders. What I can do is to copy their implementation. That's why I added their source links in the comments

https://github.com/yzhang-gh/vscode-markdown/blob/44b1e8fa413e6e7b521c940f0e2f8ad0d2dca4a9/src/util.ts#L88-L89

https://github.com/yzhang-gh/vscode-markdown/blob/44b1e8fa413e6e7b521c940f0e2f8ad0d2dca4a9/src/util.ts#L97-L98

So at least, the TOC can work on these two places. For this issue, we are addressing the upper/lower-case thing. And the outcome is we agreed to always keep the letter case. (No new option introduced)

As for the other Markdown renders, we can consider to support them if they are common enough.

---

I just checked VSCode Marketplace. A heading `Table of Contents` will have an anchor `user-content-table-of-contents`.

**Comment by yzhang-gh** [comment] 2019-05-20 09:37
What a headache. Let alone the extra `user-content-` prefix in VSC Marketplace, the current TOC doesn't work in the exported HTML now

**Comment by yzhang-gh** [comment] 2019-05-20 09:38
(misoperation)

**Comment by spmeesseman** [comment] 2019-05-20 14:20
Whaaaaaaaat???  They pre-pend "user-content-" to the anchors????  That is just plain stupid>  Whoever did that should find a new profession.

**Comment by yzhang-gh** [comment] 2019-06-16 16:01
Closing as the original issue is resolved. Now we don't downcase the TOC links.

**Closed by yzhang-gh** 2019-06-16 16:01 UTC
Labels: enhancement

**Comment by shuffle2** [comment] 2019-07-10 18:10
This breaks compat with "Markdown PDF" which is generating lowercase `id` field...

**Comment by yzhang-gh** [comment] 2019-07-10 18:27
We now have a new option to deal with it. See https://github.com/yzhang-gh/vscode-markdown/issues/476#issuecomment-508923234.

**Comment by levy9527** [comment] 2019-07-17 08:45
Well, in my situation, using lower case,  it works in github, [gitlab](https://gitlab.com/deepexi/el-input-enhance/tree/master/el-input-email#table-of-contents), npm, typora and other editors.
