### ISSUE TITLE
User-defined macros can't print to html correctly

### ISSUE THREAD

**Issue by bluethon** [yzhang-gh/vscode-markdown#579] opened 2019-12-17 03:52 UTC
#### What is the problem?
I have defined some macros in my user config, it preview in editor well, but when I print the file to HTML, it can't convert correctly, I have read #426, I have test it's code, but have the same issue

#### How can I reproduce it?
set the macro
``` json
    "markdown.extension.katex.macros": {
        "\\ci": "\\raisebox{.5pt}{\\textcircled{\\raisebox{-.9pt} {#1}}}",
    },
```
in markdown input
```
$$
\ci{1} \\
\raisebox{.5pt}{\textcircled{\raisebox{-.9pt} {1}}}
$$
```
in preview
![image](https://user-images.githubusercontent.com/3991445/70963340-1cac8000-20c3-11ea-9525-f25c26fd8104.png)
but in browser
![image](https://user-images.githubusercontent.com/3991445/70963379-377ef480-20c3-11ea-894f-9fe20d6400e4.png)

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment] 2019-12-17 15:22
Good catch. This is caused by a stupid mistake (the same as #473).

It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now.

**Comment by PaperCube** [comment] 2019-12-18 09:09
By the way, `\global\def` doesn't persist between math expressions as described in [Katex Official Documentation](https://katex.org/docs/supported.html) **unless at least one macro is defined in Settings**, which I guess is a bug as well.

**Comment by yzhang-gh** [comment] 2019-12-18 14:18
@PaperCube It doesn't look like a similar bug. Can you open a new issue and also provide a minimal working example? (A possible reason is we are still using KaTeX 0.10.0.)

**Comment by PaperCube** [comment] 2019-12-21 06:01
@yzhang-gh Issue #583 has been opened. Sorry for the delay

**Closed** 2020-01-11 07:12 UTC
Labels: bug
