### ISSUE TITLE
The relative path doesn't work for local image

### ISSUE THREAD

**Issue by cpkingw** [yzhang-gh/vscode-markdown#821] opened 2020-09-23 03:06 UTC
#### What is the problem?
The folder structure like this:
- A folder 
        --  .md
- B folder
        --  .png

The relative path "../B/.png" doesn't work, but i can use "ctrl+click" to preview the image.

**Comment by yzhang-gh** [comment] 2020-09-23 03:37
![821](https://user-images.githubusercontent.com/7588612/93963961-fd98f800-fd90-11ea-80f9-a501f49e95ec.png)

**Comment by cpkingw** [comment] 2020-09-23 11:52
Does it must include the whole folders or workplace in vscode? I just open and edit the ".md" file in vscode.

**Comment by cpkingw** [comment] 2020-09-23 11:56
Must it include the whole folder or workspace in vscode? I just open  the ".md" file in vscode without folders.

**Comment by yzhang-gh** [comment] 2020-09-23 14:45
It just occured to me that it (the preview tab) is not handled by this extension. Maybe VSCode doesn't allow you to do so.

**Comment by DiegoGFritz** [comment] 2020-10-02 15:50
I have the same problem that cpkingw has. I Just open the ".md" file in vscode without folders.
if I press ctrl+click on the link, the image show fine but ".md" preview tab cannot show the image

Example llink:
![image](https://user-images.githubusercontent.com/26330822/94942819-2ca81b80-04ad-11eb-941d-63ec1a471b29.png)

**Comment by yzhang-gh** [comment] 2020-10-02 15:55
Please check whether you get the same problem **even if this extension is disabled**. If so, you need to report this to the VSCode team.

**Comment by DiegoGFritz** [comment] 2020-10-02 15:59
Thanks for answering. I have the same problem with the extension disabled.

**Comment by Lemmingh** [comment] 2020-10-02 17:57
Confirmed. It's caused by VS Code itself:

https://github.com/microsoft/vscode/issues/98640#issuecomment-634866746

> The markdown preview can **only** load resources that **in the current workspace**

**Comment by yzhang-gh** [comment] 2020-10-03 14:20
Thanks for the information. Will close this issue as we cannot help with it.

**Closed by yzhang-gh** 2020-10-03 14:20 UTC
Labels: Out of scope, Upstream
