### ISSUE TITLE
Ordered list TOC has too little indentation (leading spaces) for items whose parent's ordinal is 10 or above

### ISSUE THREAD

**Issue by manastalukdar** [yzhang-gh/vscode-markdown#543] opened 2019-10-30 01:37 UTC
#### What is the problem?

I have `"markdown.extension.toc.orderedList": true` and `"markdown.extension.toc.levels": "2..6"`.

The document with inserted (auto-generated) toc is as follows:

```plaintext
# Dummy

1. [Dummy1](#dummy1)
2. [Dummy2](#dummy2)
3. [Dummy3](#dummy3)
   1. [Dummy3.1](#dummy31)
   2. [Dummy3.2](#dummy32)
   3. [Dummy3.3](#dummy33)
4. [Dummy4](#dummy4)
5. [Dummy5](#dummy5)
6. [Dummy6](#dummy6)
7. [Dummy7](#dummy7)
8. [Dummy8](#dummy8)
9. [Dummy9](#dummy9)
   1. [Dummy9.1](#dummy91)
   2. [Dummy9.2](#dummy92)
10. [Dummy10](#dummy10)
   1. [Dummy10.1](#dummy101)
   2. [Dummy10.2](#dummy102)
11. [Dummy11](#dummy11)
12. [Dummy12](#dummy12)
   1. [Dummy12.1](#dummy121)
   2. [Dummy12.2](#dummy122)

## Dummy1

## Dummy2

## Dummy3

### Dummy3.1

### Dummy3.2

### Dummy3.3

## Dummy4

## Dummy5

## Dummy6

## Dummy7

## Dummy8

## Dummy9

### Dummy9.1

### Dummy9.2

## Dummy10

### Dummy10.1

### Dummy10.2

## Dummy11

## Dummy12

### Dummy12.1

### Dummy12.2
```

The issue is that toc when saving and auto-updating itself aligns all the sub-items with the same spacing. Which works just fine for all sub-items with parents up to 9. However all sub-items with parent items 10 and above should have an extra space. Is there some way to configure this?

Additionally, the default initial spacing for sub-items is 3 spaces. Would be nice to be able to change this (to say, 4).

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment] 2019-10-30 04:52
> However all sub-items with parent items 10 and above should have an extra space.

I agree.

> Additionally, the default initial spacing for sub-items is 3 spaces. Would be nice to be able to change this (to say, 4).

Please try setting `markdown.extension.list.indentationSize` to `inherit`. Then the tab size can be configured per document (at the right bottom corner).

**Comment by ComFreek** [comment] 2021-02-14 13:45
> Then the tab size can be configured per document (at the right bottom corner).

@yzhang-gh Can you be a bit more specific here?

That's my right bottom corner in VS Code:

![image](https://user-images.githubusercontent.com/1827709/107878450-1d14f680-6ed3-11eb-97bf-7b765f7437f8.png)

I've tried setting the `Spaces: 2` thing to `Spaces: 1` with no effect: reprinting my Markdown to HTML afterwards still showed misformatted sublists (as described in the OP here).

**Comment by yzhang-gh** [comment] 2021-02-14 15:43
@ComFreek Please try `Spaces: 4` which means (always) indenting with 4 spaces.

> the vscode-markdown plugin simply outputs invalid Markdown. Why isn't that fixed?

Based on the feedback, it has a higher priority now 😉.

**Comment by yzhang-gh** [comment] 2021-02-16 03:36
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by ComFreek** [comment] 2021-02-17 10:20
@yzhang-gh Using the debug.vsix from the latest dev build, the command "Update TOC" seems to be broken: it doesn't have *any* effect.

![image](https://user-images.githubusercontent.com/1827709/108190286-07414480-7112-11eb-9fe7-aa414e759f34.png)

I tried issuing this command several times. Nothing happens. No errors in the console either.

**Comment by yzhang-gh** [comment] 2021-02-17 10:59
You need to "create" a TOC first 😅

**Comment by ComFreek** [comment] 2021-02-17 12:41
Oh my bad :smile:

The indentation for TOC now works for me! However, I think the generated indentation is one space too deep (even if that doesn't cause any issues):

```
1. [1](#1)
2. [2](#2)
3. [3](#3)
4. [4](#4)
5. [5](#5)
6. [6](#6)
7. [7](#7)
8. [8](#8)
9. [9](#9)
10. [A](#a)
     1. [A.1](#a1)
     2. [A.2](#a2)
11. [B](#b)
     1. [B.1](#b1)
     2. [B.2](#b2)
12. [C](#c)


# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9
# A
## A.1
## A.2
# B
## B.1
## B.2
# C
```

**Comment by yzhang-gh** [comment] 2021-02-17 14:31
Did you forget to restore `list.indentationSize` to `adaptive`?

**Comment by ComFreek** [comment] 2021-02-17 15:27
Indeed, it was still on `inherit`. Removing the configuration for `list.indentationSize` worked!

So overall, I can confirm TOC generation (wrt. indentation) works for me now like a charm! Thanks for fixing.

**Comment by yzhang-gh** [comment] 2023-04-27 17:21
Looks like it had already been fixed.

**Closed by yzhang-gh** 2023-04-27 17:21 UTC
Labels: Issue: Bug, Res: Fixed, Area: Table of contents
