### ISSUE TITLE
Erroneous text found in defaults settings.json

### ISSUE THREAD

**Issue by NerdyGriffin** [yzhang-gh/vscode-markdown#856] opened 2020-11-28 23:15 UTC
## Problem

There are erroneous lines of (what appears to be) markdown-syntax text, found in the default settings.json file. This has caused other unrelated extensions to break as a result. I have included a code block in the section below which demonstrates the problematic lines in question.
The expected behavior would be to find the normal JSON lines for the default settings.

In case it is relevant, this is on 
    Windows 10 Pro
    VSCode Version 1.51.1
    vscode-markdown Version 3.4.0

## How to reproduce

Open the settings (such as with Ctrl+,) and switch to the side-by-side JSON view. Looking in the left-side panel (the view with default settings), if you go to the section for this extension you will find the following lines:

````json
...
  // User-defined KaTeX macros.
  "markdown.extension.katex.macros": {},

  // List indentation scheme. (Also affects TOC generation.)
  // 
  // Whether to use different indentation sizes on different list contexts or stick to VS Code's tab size.
  //  - adaptive: Adaptive indentation size according to the context, trying to **left align the sublist with its parent's content**. For example:

```markdown
- Parent
  - Sublist

1. Parent
   1. Sublist

10. Parent with longer marker
    1. Sublist
    ```
  //  - inherit: Use the configured tab size of the current document (see the status bar). For example (with `tabSize: 4`):

```markdown
- Parent
    - Sublist

1. Parent
    1. Sublist

10. Parent with longer marker
    1. Sublist
 ```
  "markdown.extension.list.indentationSize": "adaptive",
...
````

Alternatively, VSCode indicates that this "default settings" view/template is accessed  via the path `\0\settings.json`

Rolling-back this extension to the previous version (3.3.0) causes the problem to go away and updating back to the latest (3.4.0) causes the problem to return.

## Error message in the console

This error does not produce any message in the console, but viewing the file as described above will allow you to see the following messages in the "PROBLEMS" view (I don't know if this is helpful, but here is it just in case)

Property keys must be doublequoted
Colon expected
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.
Unexpected end of number.

**Comment by yzhang-gh** [comment] 2020-11-29 02:05
Duplicate of #847. It has been fixed in _VS Code insiders_.

**Closed by yzhang-gh** 2020-11-29 02:05 UTC
