### ISSUE TITLE
Missing '\' after latex intelliSense

### ISSUE THREAD

**Issue by ysl970629** [yzhang-gh/vscode-markdown#860] opened 2020-12-07 13:05 UTC
**Before**
![image](https://user-images.githubusercontent.com/39717545/101354149-a7d3e680-38cf-11eb-936a-6872e47e579c.png)

**After confirming `\log` by pressing `<Enter>`**
![image](https://user-images.githubusercontent.com/39717545/101354191-b7532f80-38cf-11eb-8c4c-63c82e5ee018.png)

**The backslash disappeared.**

**Comment by Lemmingh** [comment] 2020-12-07 13:54
I cannot reproduce.

<details><summary>Environment</summary>

* Markdown All in One: 3.4.0
* VS Code: 1.51.1 (system setup)
* OS: Windows_NT x64 10.0.18363

</details>

---

There may be **some conflicts with other extensions**?

Could you please provide your environment information as described below?

1. Go to VS Code's menu **Help** > **Report issue**.
2. In the **Issue Reporter** window, set type to **Performance Issue**, set source to **Visual Studio Code**, fill other fields with arbitrary text, and make sure to check all the "Include ..." options.
3. Click **Preview on GitHub**. A GitHub issue page will be opened. You can simply close it safely.
4. **All needed data should be in your clipboard.** Paste it here.

**Comment by ysl970629** [comment] 2020-12-07 14:29
Thanks :-)
I considered if it may be plugin conflict, so I tested all my plugins and I found it is true.
The bug is caused by plugin `kortina.vscode-markdown-notes`.
I have uninstalled `kortina.vscode-markdown-notes`, everything works well now.

**Closed** 2020-12-07 14:30 UTC
Labels: Cannot reproduce, Needs more info
