### ISSUE TITLE
Plugin is conflict with aText app in Mac OS

### ISSUE THREAD

**Issue by liuhao86** [yzhang-gh/vscode-markdown#209] opened 2018-06-16 02:37 UTC
`aText` is a typing accelerate app in Mac OS.

for example, when I typed `ddate`, it will help me type `2018-06-16` instead.

when i use it in vs code, it will become `dda2018-06` or `d2018-06-1`.

if i disable this plugin `Markdown All in One`, or use other formats, such as `txt`, everything is OK.

I found error message in console, hope it will be helpful:
``` 
 ERR Cannot read property 'fromHeading' of undefined: TypeError: Cannot read property 'fromHeading' of undefined
	at Object.slugify (/Users/howard/.vscode/extensions/yzhang.markdown-all-in-one-1.4.0/out/src/util.js:47:30)
	at tocEntries.forEach.entry (/Users/howard/.vscode/extensions/yzhang.markdown-all-in-one-1.4.0/out/src/toc.js:76:81)
	at Array.forEach (native)
	at /Users/howard/.vscode/extensions/yzhang.markdown-all-in-one-1.4.0/out/src/toc.js:69:20
	at Generator.next (<anonymous>)
	at fulfilled (/Users/howard/.vscode/extensions/yzhang.markdown-all-in-one-1.4.0/out/src/toc.js:4:58)
	at <anonymous>
```

**Comment by Lemmingh** [comment] 2021-09-05 16:34
Closing as a duplicate of #200

**Closed by Lemmingh** 2021-09-05 16:34 UTC
Labels: Res: Duplicate, Area: Input
