### ISSUE TITLE
Issues with using omittedFromToc setting on Windows

### ISSUE THREAD

**Issue by axxie** [yzhang-gh/vscode-markdown#644] opened 2020-03-24 10:22 UTC
I would like to report some issues with using `omittedFromToc` setting on Windows.

1. Paths relative to the workspace do not work in `omittedFromToc` setting on Windows. The extension contains the code that attempts to change portion of the `doc.fileName` to an empty string for future search using relative path. It uses a string with absolute workspace path and slash character as a search pattern for `replace`. However, on Windows the doc.fileName contains backslash character, not slash, so the replace does not work. Because of this, the workspace relative paths do not work. The mentioned code is here:
https://github.com/yzhang-gh/vscode-markdown/blob/7d7d9d9fc7d108b0a64477b9a46d130524c61b15/src/toc.ts#L78-L83
2. The replace and search in the settings is case-sensitive. However, the paths on Windows are mostly case-insensitive. 

For now, the only way to use `omittedFromToc` setting on Windows is to use absolute paths and use non-capital character for drive letter (the first one in path), like this:
```json
{
    "settings": {
        "markdown.extension.toc.omittedFromToc": {
            "c:\\MyProjects\\project\\README.md": [
                "## Table of contents"
            ]
        }
    }
}
```

**Comment by yzhang-gh** [comment] 2020-03-24 14:45
Thanks for your suggestion. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by i-keliukh** [comment] 2020-03-27 07:07
> Thanks for your suggestion. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

I checked the fix.
1. The issue with drive letter is fixed.
2. The issue with relative path is **not** fixed.

The reason is still slash character in the `replace`:
https://github.com/yzhang-gh/vscode-markdown/blob/62b0af52925ca8d635f24b2a87d42e5a363323d9/src/toc.ts#L87-L89

`doc.filename` contains backslashes, not slashes, so `replace` cannot find the workspace path with slash.

**Comment by yzhang-gh** [comment] 2020-03-27 09:43
Thanks!

I was trying to patch this part of code which came from a PR 😂. I have reworked it and now it should work better.

**Comment by i-keliukh** [comment] 2020-03-27 10:52
I confirm that the issue is fixed

**Closed** 2020-06-20 02:22 UTC
Labels: Area: table of contents, Bug, Fixed in dev build
