### ISSUE TITLE
Table of contents not recognized if indented.

### ISSUE THREAD

**Issue by brunnerh** [yzhang-gh/vscode-markdown#830] opened 2020-10-05 09:31 UTC
## Problem
A table of contents is not recognized as such if it is indented, e.g. within a `<details>` section.
(Code lens is missing and the update ToC command does not update it.)

## How to reproduce

Example file:

```markdown
# Test File

<details>
  <summary>Table of contents</summary>

  - [Test File](#test-file)
    - [SubHeading 1](#subheading-1)
    - [SubHeading 2](#subheading-2)
</details>

## SubHeading 1

## SubHeading 2
```

**Comment by yzhang-gh** [comment] 2020-10-05 12:38
It is true that a list can be indented (with less than 4 spaces). But personally I would suggest not indenting _a TOC_.

**Comment by brunnerh** [comment] 2020-10-05 16:50
It is indented because it is inside of a tag (so it lines up with `summary` as well).
Sure, it is not necessary, i just think it looks nicer.

**Comment by yzhang-gh** [comment] 2020-10-06 09:12
> i just think it looks nicer.

I see. The problem is there is no spec for the mix usage of Markdown and HTML. (Indentation is (almost) meaningless in HTML but for Markdown it is not true.) I always use 4-space indentation in HTML, apparently it will cause a problem in this case.
In practice, I don't indent the `summary` tag If it is used it in Markdown.

(I'm not very motivated to change the current behavior. Leaving this open to see if anyone would like to help.)

**Comment by brunnerh** [comment] 2020-10-06 15:15
It probably makes no sense to change this. You can also nest multiple `details` and sooner or later the indentation will cause the content to be interpreted as code.

**Comment by Lemmingh** [comment] 2021-01-17 15:13
I think this problem is **nothing to do with HTML blocks**.

The example above is parsed as 6 blocks:

1. Heading level 1, `[0, 1]`.
2. Type 6 HTML block, `[2, 4]`.
3. Bullet list, `[5, 8]`.
4. Type 6 HTML block, `[8, 9]`.
5. Heading level 2, `[10, 11]`.
6. Heading level 2, `[12, 13]`.

Important facts:

* A Type 6 HTML block is terminated by a **blank line**.
* CommonMark asks parsers to pass HTML blocks as is, and perform normal Markdown parsing in other parts.

So, the existence of HTML blocks does **not** affect **how a parser recognizes the list between them**.

---

After #877, `detectTocRanges()` will recognize the list in this example as a TOC. Then, I'm going to close this.

**Closed** 2021-01-17 16:26 UTC
Labels: Area: table of contents, Under discussion
