### ISSUE TITLE
Going back to source file on double click behavior should be an option

### ISSUE THREAD

**Issue by Combinacijus** [yzhang-gh/vscode-markdown#1048] opened 2021-11-19 17:13 UTC
## Problem
When in preview mode (ctrl+shift+v) double clicking changes tab to .md file

## Proposal
Going back to source file on double click behavior should be an option or disabled.

## Why
Usually I open file preview for nice formatting and double clicking to select full word and then full text/command to copy. But I'm sent back to source which is not what I wanted. So I have to copy from source file or don't use double click which is in my muscle memory

**Comment by Lemmingh** [comment] 2021-11-19 18:36
`markdown.preview.doubleClickToSwitchToEditor`

Duplicate of #568

The [Markdown preview](https://code.visualstudio.com/docs/languages/markdown) is provided by VS Code, please check [its docs](https://code.visualstudio.com/docs/getstarted/settings) first.

**Closed by Lemmingh** 2021-11-19 18:36 UTC
Labels: Issue: Question, Res: External, Area: Preview
