### ISSUE TITLE
Does not work with UTF-8

### ISSUE THREAD

**Issue by Smithienious** [yzhang-gh/vscode-markdown#1009] opened 2021-09-05 14:47 UTC
Related: #287

## Problem

I am trying to type Vietnamese characters, but the extension doesn't seem to recognize the characters and decides to block the new characters completely.

This only occurs if you are using a Vietnamese input method program. Pasting the characters still work.

## How to reproduce

Reproducible on both UniKey and EVKey. The following uses UniKey.

1. Download the latest version from [the mainpage](https://www.unikey.org/download.html) or [SourceForge](https://sourceforge.net/projects/unikey/)
2. Extract and run `UniKeyNT.exe`
3. Its icon is now in the taskbar and showing `E`. Click it once and it will turn into `V`, indicating the program is now in Vietnamese type mode.
4. Using its default settings (Unicode, Telex), type in VSCode some sample strings

| Input    | oo   | ow   | oof  | aws  | thooi | khongo | rooif |
| :------- | :--- | :--- | :--- | :--- | :---- | :----- | :---- |
| Expected | ô    | ơ    | ồ    | ắ    | thôi  | không  | rồi   |

## Configuration

The only Md related settings is

```jsonc
  "files.associations": {
    ".gitignore": "ignore",
    "*.rmd": "markdown",
    "**/*.html": "html",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements",
    "**/templates/**/*": "django-txt",
    "**/templates/**/*.html": "django-html"
  },
```

<details><summary>Full settings</summary>

```jsonc
{
  "[latex]": {
    "editor.defaultFormatter": "James-Yu.latex-workshop"
  },
  "C_Cpp.updateChannel": "Insiders",
  "cmake.configureOnOpen": false,
  "cSpell.language": "en,vi",
  "debug.onTaskErrors": "showErrors",
  "diffEditor.codeLens": true,
  "editor.acceptSuggestionOnEnter": "off",
  "editor.bracketPairColorization.enabled": true,
  "editor.cursorBlinking": "expand",
  "editor.cursorSmoothCaretAnimation": true,
  "editor.cursorStyle": "block",
  "editor.fontFamily": "Victor Mono",
  "editor.fontLigatures": true,
  "editor.minimap.showSlider": "always",
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.renderWhitespace": "trailing",
  "editor.suggest.preview": true,
  "editor.suggestSelection": "recentlyUsedByPrefix",
  "emmet.includeLanguages": {
    "django-html": "html"
  },
  "emmet.triggerExpansionOnTab": true,
  "errorLens.enabledDiagnosticLevels": [
    "error",
    "warning",
    "hint",
    "info"
  ],
  "errorLens.messageTemplate": "$severity [1/$count] $message",
  "errorLens.severityText": [
    "(っ °Д °;)っ",
    "(* ￣︿￣)",
    "（︶^︶）",
    "( ͡° ͜ʖ ͡°)"
  ],
  "explorer.confirmDragAndDrop": false,
  "files.associations": {
    ".gitignore": "ignore",
    "*.rmd": "markdown",
    "**/*.html": "html",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements",
    "**/templates/**/*": "django-txt",
    "**/templates/**/*.html": "django-html"
  },
  "files.autoSave": "onFocusChange",
  "git.enableCommitSigning": true,
  "git.smartCommitChanges": "tracked",
  "git.untrackedChanges": "separate",
  "githubPullRequests.fileListLayout": "tree",
  "howIVSCode.userIdentificationKey": "",
  "html.format.indentInnerHtml": true,
  "latex-workshop.chktex.delay": 1000,
  "latex-workshop.chktex.enabled": true,
  "latex-workshop.chktex.run": "onType",
  "latex-workshop.latex.tools": [
    {
      "args": [
        "--shell-escape",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "%DOC%"
      ],
      "command": "latexmk",
      "env": {},
      "name": "latexmk"
    },
    {
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-lualatex",
        "-outdir=%OUTDIR%",
        "%DOC%"
      ],
      "command": "latexmk",
      "env": {},
      "name": "lualatexmk"
    },
    {
      "args": [
        "%DOC%"
      ],
      "command": "latexmk",
      "env": {},
      "name": "latexmk_rconly"
    },
    {
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
      ],
      "command": "pdflatex",
      "env": {},
      "name": "pdflatex"
    },
    {
      "args": [
        "%DOCFILE%"
      ],
      "command": "bibtex",
      "env": {},
      "name": "bibtex"
    },
    {
      "args": [
        "-e",
        "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
      ],
      "command": "Rscript",
      "env": {},
      "name": "rnw2tex"
    },
    {
      "args": [
        "-e",
        "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
      ],
      "command": "julia",
      "env": {},
      "name": "jnw2tex"
    },
    {
      "args": [
        "-e",
        "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
      ],
      "command": "julia",
      "env": {},
      "name": "jnw2texmintex"
    },
    {
      "args": [
        "--synctex",
        "--keep-logs",
        "%DOC%.tex"
      ],
      "command": "tectonic",
      "env": {},
      "name": "tectonic"
    }
  ],
  "latex-workshop.view.pdf.viewer": "tab",
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "python.insidersChannel": "weekly",
  "python.languageServer": "Pylance",
  "redhat.telemetry.enabled": true,
  "search.exclude": {
    "**/.venv": true
  },
  "security.workspace.trust.enabled": false,
  "shellformat.useEditorConfig": true,
  "sync.gist": "",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.defaultProfile.linux": "zsh",
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "args": [
        "-l"
      ],
      "icon": "terminal-bash",
      "path": "bash"
    },
    "zsh": {
      "args": [
        "-l"
      ],
      "icon": "terminal-bash",
      "path": "zsh"
    }
  },
  "thunder-client.codeSnippetLanguage": "cs-httpclient",
  "todo-tree.general.tags": [
    "BUG",
    "HACK",
    "FIXME",
    "TODO",
    "XXX",
    "[ ]",
    "[x]"
  ],
  "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",
  "workbench.colorTheme": "Monokai Pro",
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook",
    "*.pdf": "latex-workshop-pdf-hook"
  },
  "workbench.iconTheme": "ayu",
  "workbench.productIconTheme": "icons-carbon",
  "workbench.sideBar.location": "right"
}
```

</details>

## Environment

v3.4.0

```text
Released on
05/01/2017, 21:15:01
Last updated
14/11/2020, 10:12:10
Identifier
yzhang.markdown-all-in-one
```

```text
Version: 1.61.0-insider (user setup)
Commit: 87260247dc7b912db6e6a21a366e6f50dca759ba
Date: 2021-09-03T20:58:36.778Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

## Diagnostic data

Not applicable

**Comment by yzhang-gh** [comment] 2021-09-05 15:45
Please see whether https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661 helps.

**Comment by Lemmingh** [comment] 2021-09-05 16:32
Duplicate of #200

**Closed by Lemmingh** 2021-09-05 16:32 UTC
Labels: Res: Duplicate, Area: Input

**Comment by Smithienious** [comment] 2021-09-05 17:44
@yzhang-gh @Lemmingh that's a long list of issues. Maybe it's time to put in the FAQ as a known issue.

**Comment by Lemmingh** [comment] 2021-09-06 12:43
<https://markdown-all-in-one.github.io/docs/guide/compatibility.html>
Added a new article, as it's too long.

**Comment by Lemmingh** [comment] 2021-10-14 05:17
@Smithienious
I wonder if there's anything special in Vietnamese, blocking those IMEs from taking advantage of Composition Mode.

Normally, at least in CJK, an IME triggers Composition Mode to show that it's constructing some characters, so that the host will kindly wait and not dispatch any key binding event. I'm pretty surprised that Vietnamese IMEs don't ues Composition.

**Comment by Smithienious** [comment] 2021-10-14 08:26
@Lemmingh I believe that is due to backwards compatibility for older programs.

I tried this little script

```python
from unicodedata import normalize

def unorm(str):
    print(normalize('NFC', str))
    print(normalize('NFKC', str))
    print(normalize('NFD', str))
    print(normalize('NFKD', str))

if __name__ == '__main__':
    unorm(u'à')
    unorm(u'ồ')
    unorm(u'ắ')
    unorm(u'thôi')
    unorm(u'không')
    unorm(u'rồi')
```

Windows Terminal and VSCode terminal are not the same.

<details><summary>VSCode</summary>

![image](https://user-images.githubusercontent.com/10150902/137279554-03403b2a-e164-4881-9622-56c431157552.png)

</details>

<details><summary>Windows Terminal</summary>

![image](https://user-images.githubusercontent.com/10150902/137279616-e1816488-25df-4302-a055-d9d5617a7218.png)

</details>

[Unikey tracks issues on another site](https://sourceforge.net/projects/unikey/), maybe I will contact the author. If possible, I will go through their source code. Any further discussion about Unicode at this point is beyond my knowledge.

**Comment by polypores** [comment] 2024-05-19 04:22
#617 I tried this. It also worked for Vietnamese with EVKey.
