### ISSUE TITLE
**bold** keyboard shortcut conflicts with View > Appearance > Show Side Bar

### ISSUE THREAD

**Issue by kortina** [yzhang-gh/vscode-markdown#635] opened 2020-03-12 22:58 UTC
#### What is the problem?

The contributed keybinding `cmd+b` on Mac conflicts with the default keybinding to show / hide the Side Bar.

#### How can I reproduce it?

On Mac, in a markdown file, type `cmd+b` in a Markdown file this will toggle bold, not the Side Bar.

Is there any way to disable the bold keybinding contributed by this plugin?

**Comment by yzhang-gh** [comment] 2020-03-13 02:10
Thanks for the feedback. This is a duplicate of #89.

In short, it is hard to strike a balance among different preferences of all users. I would suggest reassigning this keybinding by yourself.

**Closed by yzhang-gh** 2020-03-13 02:10 UTC

**Comment by kortina** [comment] 2020-03-14 00:02
Thanks.

In addition to remapping the extension keybinding, I had to remap the default to get this to work:

```json
    // cmd+b, the default, is the built in shortcut to
    // Hide / Show Side Bar, so release extension binding:
    {
        "key": "cmd+alt+b",
        "command": "markdown.extension.editing.toggleBold",
    },
    {
        "key": "cmd+b",
        "command": "workbench.action.toggleSidebarVisibility",
    },
```
