### ISSUE TITLE
Suggestion: Drag'n drop support for images 

### ISSUE THREAD

**Issue by Jarzka** [yzhang-gh/vscode-markdown#768] opened 2020-07-31 14:36 UTC
Drag'n dropping images directly in Markdown text would make it much easier to include images in Markdown without writing file names. Would it be possible to implement such a functionality?

**Comment by yzhang-gh** [comment] 2020-07-31 15:15
AFAIK, VSCode doesn't provide such kind of APIs 🤔. (duplicate of #749)

**Closed** 2020-08-09 03:35 UTC
Labels: Duplicate
