### ISSUE TITLE
The highlight disappeared after updating the software

### ISSUE THREAD

**Issue by ChnTamap** [yzhang-gh/vscode-markdown#1010] opened 2021-09-06 01:47 UTC
Hi,   

After I update the vscode to 1.60.0, the highlight of markdown disappeared.  

![p1](https://user-images.githubusercontent.com/36532501/132149122-0468998c-7719-4850-b94e-a656f73855c3.png)

And when Markdown All in One is disable, the highlight work again.

![p2](https://user-images.githubusercontent.com/36532501/132149271-c32fc6e0-3d0c-4479-b478-423dd6a07d10.png)

My extension list:

- Latex language support
- Markdown All in One
- Markdown Preview Enhanced
- Waveform Render
- XML Tools
- ActionScript \& MXML
- Bracket Pair Colorizer
- Doxygen Documentation Generator
- Git Graph
- Jupyter Keymap

**Comment by Lemmingh** [comment] 2021-09-06 02:56
Would you please try:

1. Uninstall Markdown All in One.

2. Reload VS Code completely: Close all VS Code instances (if on macOS, remember to Control-click the Dock icon and select Quit at last), then restart it.

3. Install Markdown All in One.

4. Reload VS Code.

Besides, is there any dollar signs (`$`) in your document? #1008

**Comment by Lemmingh** [comment] 2021-09-06 03:04
Additionally, would you please run the VS Code command "Developer: Inspect Editor Tokens and Scopes" via Command Palette, then, move cursor to check highlighting tokens in the document?

**Comment by ChnTamap** [comment] 2021-09-06 11:15
> 
> 
> Would you please try:
> 
>     1. Uninstall Markdown All in One.
> 
>     2. Reload VS Code completely: Close all VS Code instances (if on macOS, remember to Control-click the Dock icon and select Quit at last), then restart it.
> 
>     3. Install Markdown All in One.
> 
>     4. Reload VS Code.
> 
> 
> Besides, is there any dollar signs (`$`) in your document? #1008

Thank you for your reply!   

Yes there are many LaTeX code in the document. And the highlight work again when I remove the dollar signs. Can you give me some advice?

**Comment by Lemmingh** [comment] 2021-09-06 12:52
#1008 might provide a solution.

**Comment by Lemmingh** [comment] 2021-09-26 06:48
Duplicate of #1008

**Closed by Lemmingh** 2021-09-26 06:48 UTC
Labels: Res: Duplicate, Area: Math, Area: Editor theming
